### ISSUE TITLE
travis.yml and minimum engine mismatch

### ISSUE THREAD

**Issue by niklasR** [bbc/http-transport-cache#26]
Travis runs tests in the latest version of node 8 as minimum: https://github.com/bbc/http-transport-cache/blob/212bb0339ef79586cb77fa052e7e103a997a8bea/.travis.yml#L6

The package.json specifies v4.0.0 as minimum: https://github.com/bbc/http-transport-cache/blob/212bb0339ef79586cb77fa052e7e103a997a8bea/package.json#L12

`assert.doesNotReject` and `assert.rejects` were only added in 8.13.0, so tests may fail on versions that the the `package.json` allows, but this would not be flagged by Travis.

**Comment by davidc6** [comment]
Fixed in https://github.com/bbc/http-transport-cache/pull/27

**Comment by nspragg** [comment]
@davidc6 - thanks 👍
